name: Rust publish

on:
  release:
    published:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build -j 2 --all-targets && cargo build -j 2 --all-features --all-targets
    - name: Run tests
      run: cargo test -j 2 && cargo test -j 2 --all-features
    - name: Publish derive package
      run: cargo publish -j 2 -p polars-rows-iter-derive --dry-run 
      env:
        CARGO_REGISTRY_TOKEN: ${{ secrets.CRATES }}
    - name: Publish main package
      run: cargo publish -j 2 -p polars-rows-iter --dry-run 
      env:
        CARGO_REGISTRY_TOKEN: ${{ secrets.CRATES }}
        